MM_SCREEN = 512				; Screen RAM (40x24)
MM_COLUMNS = 1472			; Screen width
MM_ROWS = 1473				; Screen height
MM_KEY = 1474				; Current key pressed
MM_RANDOM = 1475			; Random number generator
MM_CLOCK = 1476				; Clock (just counts seconds)
MM_DISK_FILENAME = 1477		; Pointer to start of file read/write string
MM_DISK_BUFFER_START = 1479	; Pointer to start of read/write buffer
MM_DISK_BUFFER_END = 1481	; Pointer to end of read/write buffer
MM_DISK_STATUS = 1483		; Disk drive status and character set:
MM_USER = 1484				; Start of user code
