test1:
	clear && dasm ./test1.asm -otest1.rig -f3 || exit 1
	../../geekrig4000 ./test1.rig

tic-tac-tie:
	clear && dasm ./tic-tac-tie.asm -otic-tac-tie.rig -f3 || exit 1
	../../geekrig4000 ./tic-tac-tie.rig

kernel-test:
	clear && dasm ./kernel-test.asm -okernel-test.rig -f3 || exit 1
	../../geekrig4000 ./kernel-test.rig

invaders:
	clear && dasm ./invaders.asm -oinvaders.rig -f3 || exit 1
	../../geekrig4000 ./invaders.rig
