; TIC-TAC-TIE - obviousy, a tic-tac-toe clone :)
; ==========================================================================================================================================================
;
; POINTERS:
;	$00-$05		Used for drawing stuff
;	$FF			The player's choice (X or O)
; ==========================================================================================================================================================

	ORG $05CC
	PROCESSOR 6502
	include "geekrig4000/memory-map.asm"

MAIN:
	JSR CLEAR_BOARD
	JSR TITLE_SCREEN
	JSR CLEAR_TITLE
	JSR DRAW_BOARD
	JSR GAME_SCREEN
	JMP MAIN

CLEAR_BOARD:
	LDA #<BOARD_LINE_1
	STA $00
	LDA #>BOARD_LINE_1
	STA $01
	LDA #<BOARD_LINE_2
	STA $02
	LDA #>BOARD_LINE_2
	STA $03
	LDA #<BOARD_LINE_3
	STA $04
	LDA #>BOARD_LINE_3
	STA $05
	LDY #0
	LDA #KEY_SPACE
CLEAR_BOARD_LOOP:
	STA SCREEN + 15,Y
	STA SCREEN + 55,Y
	STA SCREEN + 175,Y
	STA SCREEN + 215,Y
	STA SCREEN + 335,Y
	STA SCREEN + 375,Y
	STA SCREEN + 95,Y
	STA SCREEN + 255,Y
	STA SCREEN + 135,Y
	STA SCREEN + 295,Y
	INY
	CPY #10
	BNE CLEAR_BOARD_LOOP
	RTS

CLEAR_TITLE:
	LDA #<TITLE_SCREEN_LINE_1
	STA $00
	LDA #>TITLE_SCREEN_LINE_1
	STA $01
	LDA #<TITLE_SCREEN_LINE_2
	STA $02
	LDA #>TITLE_SCREEN_LINE_2
	STA $03
	LDA #PETSCII_SPACE
	LDY #0
GAME_SCREEN_CLEAR_TITLE_LOOP:
	STA SCREEN + 13,Y
	STA SCREEN + 53,Y
	INY
	CPY #14
	BNE GAME_SCREEN_CLEAR_TITLE_LOOP
	RTS

TITLE_SCREEN:
	LDA #<TITLE_SCREEN_LINE_1
	STA $00
	LDA #>TITLE_SCREEN_LINE_1
	STA $01
	LDA #<TITLE_SCREEN_LINE_2
	STA $02
	LDA #>TITLE_SCREEN_LINE_2
	STA $03
	LDY #0
GAME_SCREEN_DRAW_TITLE_LINE_1:
	LDA ($00),Y
	STA SCREEN + 13,Y
	LDA ($02),Y
	STA SCREEN + 53,Y
	INY
	CPY #14
	BNE GAME_SCREEN_DRAW_TITLE_LINE_1
GAME_SCREEN_X_OR_O:
	LDA KEY
	CMP #KEY_X
	BEQ GAME_SCREEN_DONE
	CMP #KEY_O
	BEQ GAME_SCREEN_DONE
	JMP GAME_SCREEN_X_OR_O
GAME_SCREEN_DONE:
	STA $FF
	JSR CLEAR_TITLE
	RTS

GAME_SCREEN:
	LDA KEY
	CMP #KEY_ESCAPE
	BNE GAME_SCREEN
	JSR CLEAR_BOARD
	RTS

DRAW_BOARD:
	LDA #<BOARD_LINE_1
	STA $00
	LDA #>BOARD_LINE_1
	STA $01
	LDA #<BOARD_LINE_2
	STA $02
	LDA #>BOARD_LINE_2
	STA $03
	LDA #<BOARD_LINE_3
	STA $04
	LDA #>BOARD_LINE_3
	STA $05
	LDY #0
DRAW_BOARD_LOOP:
	LDA ($00),Y
	STA SCREEN + 15,Y
	STA SCREEN + 55,Y
	STA SCREEN + 175,Y
	STA SCREEN + 215,Y
	STA SCREEN + 335,Y
	STA SCREEN + 375,Y
	LDA ($02),Y
	STA SCREEN + 95,Y
	STA SCREEN + 255,Y
	LDA ($04),Y
	STA SCREEN + 135,Y
	STA SCREEN + 295,Y
	INY
	CPY #10
	BNE DRAW_BOARD_LOOP
DRAW_BOARD_NUMBERS:
	LDX #PETSCII_7
	STX SCREEN + 15
	INX
	STX SCREEN + 19
	INX
	STX SCREEN + 23
	LDX #PETSCII_4
	STX SCREEN + 175
	INX
	STX SCREEN + 179
	INX
	STX SCREEN + 183
	LDX #PETSCII_1
	STX SCREEN + 335
	INX
	STX SCREEN + 339
	INX
	STX SCREEN + 343
	RTS


; HOLY SMOKE THIS ACTUALLY WORKED! :d
; IDEA:
	; $00-$01 = character to draw
;	LDA #<BOARD_O
;	STA $00
;	LDA #>BOARD_O
;	STA $01
;	LDY #0
;	JSR DRAW_1
;	LDY #0
;	JSR DRAW_2
;	LDY #0
;	JSR DRAW_3
;	LDY #0
;	JSR DRAW_4
;	LDY #0
;	JSR DRAW_5
;	LDY #0
;	JSR DRAW_6
;	LDY #0
;	JSR DRAW_7
;	LDY #0
;	JSR DRAW_8
;	LDY #0
;	JSR DRAW_9
;	JMP IDEA	; for now

DRAW_7:
	LDA ($00),Y
	STA SCREEN + 15
	INY
	LDA ($00),Y
	STA SCREEN + 16
	INY
	LDA ($00),Y
	STA SCREEN + 55
	INY
	LDA ($00),Y
	STA SCREEN + 56
	RTS

DRAW_8:
	LDA ($00),Y
	STA SCREEN + 19
	INY
	LDA ($00),Y
	STA SCREEN + 20
	INY
	LDA ($00),Y
	STA SCREEN + 59
	INY
	LDA ($00),Y
	STA SCREEN + 60
	RTS

DRAW_9:
	LDA ($00),Y
	STA SCREEN + 23
	INY
	LDA ($00),Y
	STA SCREEN + 24
	INY
	LDA ($00),Y
	STA SCREEN + 63
	INY
	LDA ($00),Y
	STA SCREEN + 64
	RTS

DRAW_4:
	LDA ($00),Y
	STA SCREEN + 175
	INY
	LDA ($00),Y
	STA SCREEN + 176
	INY
	LDA ($00),Y
	STA SCREEN + 215
	INY
	LDA ($00),Y
	STA SCREEN + 216
	RTS

DRAW_5:
	LDA ($00),Y
	STA SCREEN + 179
	INY
	LDA ($00),Y
	STA SCREEN + 180
	INY
	LDA ($00),Y
	STA SCREEN + 219
	INY
	LDA ($00),Y
	STA SCREEN + 220
	RTS

DRAW_6:
	LDA ($00),Y
	STA SCREEN + 183
	INY
	LDA ($00),Y
	STA SCREEN + 184
	INY
	LDA ($00),Y
	STA SCREEN + 223
	INY
	LDA ($00),Y
	STA SCREEN + 224
	RTS

DRAW_1:
	LDA ($00),Y
	STA SCREEN + 335
	INY
	LDA ($00),Y
	STA SCREEN + 336
	INY
	LDA ($00),Y
	STA SCREEN + 375
	INY
	LDA ($00),Y
	STA SCREEN + 376
	RTS

DRAW_2:
	LDA ($00),Y
	STA SCREEN + 339
	INY
	LDA ($00),Y
	STA SCREEN + 340
	INY
	LDA ($00),Y
	STA SCREEN + 379
	INY
	LDA ($00),Y
	STA SCREEN + 380
	RTS

DRAW_3:
	LDA ($00),Y
	STA SCREEN + 343
	INY
	LDA ($00),Y
	STA SCREEN + 344
	INY
	LDA ($00),Y
	STA SCREEN + 383
	INY
	LDA ($00),Y
	STA SCREEN + 384
	RTS



TITLE_SCREEN_LINE_1:	; "TIC-TAC-TIE :)"
	BYTE $14,$09,$03,$2D,$14,$01,$03,$2D,$14,$09,$05,$20,$3A,$29
TITLE_SCREEN_LINE_2:	; " PRESS X OR O"
	BYTE $20,$10,$12,$05,$13,$13,$20,$18,$20,$0F,$12,$20,$0F
BOARD_LINE_1:	; Like "  |  |  "
	BYTE $20,$20,$E1,$61,$20,$20,$E1,$61,$20,$20
BOARD_LINE_2:	; Top half of a horizontal line, like "--+--+--"
	BYTE $62,$62,$FE,$FC,$62,$62,$FE,$FC,$62,$62
BOARD_LINE_3:	; Bottom half of the horizontal line
	BYTE $E2,$E2,$FB,$EC,$E2,$E2,$FB,$EC,$E2,$E2
BOARD_X:		; The X character, 2x2 chars, from top left to bottom right (so like \//\)
	BYTE $4D,$4E,$4E,$4D
BOARD_O:		; The O character, done the same way
	BYTE $55,$49,$4A,$4B
